spring.application.name=MybatisSample

spring.datasource.url=jdbc:mysql://localhost/sampledb
# 接続する MySQL の場所（URL）を指定しています。
# 分解すると：
# jdbc:mysql:// → MySQL に接続するよ
# localhost → 自分の PC の MySQL に接続する
# sampledb → 接続先のデータベース名
# つまり…
# あなたの PC の MySQL にある sampledb というデータベースに接続する設定
spring.datasource.username=root
# MySQL の ユーザー名
spring.datasource.password=Nakano@5532
# MySQL の 接続パスワード。root ユーザーに設定したパスワー
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Java が MySQL に接続する時に使う ドライバー（運転手） を指定しています。
# これは MySQL の公式ドライバーなので、このままでOK。
mybatis.configuration.map-underscore-to-camel-case=true
# ☆重要☆
# テーブルのカラム名（snake_case）を、Java のフィールド名（camelCase）に自動変換する
# 例）MySQLで以下のカラムがあるとする
# user_id、user_name、create_date
# ↑をJavaのフィールドでは以下の様に書き方を変えないといけない
# private int userId;、private String userName;、private LocalDate createDate;
# 上記をMybatisが自動で変換してくれる